### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by aaronburk** [USDAForestService/fs-open-forest#32]
The Christmas tree module and Special use links are broken on the Intro page
![image](https://user-images.githubusercontent.com/25828899/46171494-b265b080-c26e-11e8-830d-9f9ff5fea494.png)
https://github.com/18F/fs-open-forest/wiki

**Comment by davemcorwin** [comment]
@aaronburk please review updated links.

**Comment by aaronburk** [comment]
Aaron needs to review what information may or may not have been lost in trnasiiton on this  card.  He thinks it may related ot having a link to RFQ for initial modules
