### ISSUE TITLE
Add Images to debug

### ISSUE THREAD

**Issue by lauraGgit** [USDAForestService/fs-open-forest#35]
![image](https://user-images.githubusercontent.com/5840989/48585954-50cfd300-e8fc-11e8-84ae-45f1147ac82d.png)

![image](https://user-images.githubusercontent.com/5840989/48585966-5af1d180-e8fc-11e8-860c-d750dbcf7623.png)

![image](https://user-images.githubusercontent.com/5840989/48585976-5fb68580-e8fc-11e8-93df-fcc13ad585ad.png)

![image](https://user-images.githubusercontent.com/5840989/48586016-8f658d80-e8fc-11e8-8f05-cc7d0a08ebaa.png)

**Comment by davemcorwin** [comment]
@lauraGgit can this be closed?
